tragedy = "tragedy"
comedy = "comedy"
history = "history"

plays = {
    "1H4.xml": {"genre": history, "full_name": "Henry IV part 1"},
    "1H6.xml" : {"genre": history, "full_name": "Henry VI part 1"},
    "2H4.xml" : {"genre": history, "full_name": "Henry IV part 2"},
    "2H6.xml" : {"genre": history, "full_name": "Henry VI part 2"},
    "3H6.xml" : {"genre": history, "full_name": "Henry VI part 3"},
    "Ado.xml" : {"genre": comedy, "full_name": "Much Ado About Nothing"},
    "Ant.xml" : {"genre": tragedy, "full_name": "Antony and Cleopatra"},
    "AWW.xml" : {"genre": comedy, "full_name": "All's Well That Ends Well"},
    "AYL.xml" : {"genre": comedy, "full_name": "As You Like It"},
    "Cor.xml" : {"genre": tragedy, "full_name": "Coriolanus"},
    "Cym.xml" : {"genre": comedy, "full_name": "Cymbeline"},
    "Err.xml" : {"genre": comedy, "full_name": "The Comedy of Errors"},
    "H5.xml" : {"genre": history, "full_name": "Henry V"},
    "H8.xml" : {"genre": history, "full_name": "Henry VIII"},
    "Ham.xml" : {"genre": tragedy, "full_name": "Hamlet"},
    "JC.xml" : {"genre": tragedy, "full_name": "Julius Caesar"},
    "Jn.xml" : {"genre": history, "full_name": "King John"},
    "LLL.xml" : {"genre": comedy, "full_name": "Love's Labours Lost"},
    "Lr.xml" : {"genre": tragedy, "full_name": "King Lear"},
    "Mac.xml" : {"genre": tragedy, "full_name": "Macbeth"},
    "MM.xml" : {"genre": comedy, "full_name": "Measure for Measure"},
    "MND.xml" : {"genre": comedy, "full_name": "Midsummer Night's Dream"},
    "MV.xml" : {"genre": tragedy, "full_name": "Merchant of Venice"},
    "Oth.xml" : {"genre": tragedy, "full_name": "Othello"},
    "Per.xml" : {"genre": comedy, "full_name": "Pericles"},
    "R2.xml" : {"genre": history, "full_name": "Richard II"},
    "R3.xml" : {"genre": history, "full_name": "Richard III"},
    "Rom.xml" : {"genre": tragedy, "full_name": "Romeo and Juliet"},
    "Shr.xml" : {"genre": comedy, "full_name": "Taming of the Shrew"},
    "TGV.xml" : {"genre": comedy, "full_name": "Two Gentlemen of Verona"},
    "Tim.xml" : {"genre": tragedy, "full_name": "Timon of Athens"},
    "Tit.xml" : {"genre": tragedy, "full_name": "Titus Andronicus"},
    "Tmp.xml" : {"genre": comedy, "full_name": "The Tempest"},
    "TN.xml" : {"genre": comedy, "full_name": "Twelfth Night"},
    "Tro.xml" : {"genre": comedy, "full_name": "Troilus and Cressida"},
    "Wiv.xml" : {"genre": comedy, "full_name": "Merry Wives of Windsor"},
    "WT.xml" : {"genre": tragedy, "full_name": "Winter's Tale"},
}